### ISSUE TITLE
Error when passing a SauceLabs browser

### ISSUE THREAD

**Issue by verlok** [brunoscopelliti/marvin#7]
Hi,
I'm passing this value to the `browsers` property in the config.json:

```json
[{
    "seleniumServer": "http://ondemand.saucelabs.com:80/wd/hub",
    "username": "#############",
    "accessKey": "#######################",
    "browserName": "safari",
    "platform": "OS X 10.10",
    "version": "8.0"
}]
```

But I get the following error in console:

```console
Warning: Command failed:
C:\Code\marvin-demo\node_modules\marvin-js\node_modules\selenium-webdriver\lib\goog\async\nexttick.js:39
  goog.global.setTimeout(function() { throw exception; }, 0);
                                            ^
Error: Unable to find Safari on the current system
    at Error (<anonymous>)
    at C:\Code\marvin-demo\node_modules\marvin-js\node_modules\selenium-webdriver\safari.js:202:17
    at promise.ControlFlow.runInFrame_ (eval at <anonymous> (C:\Code\marvin-demo\node_modules\marvin-js\node_modules
\selenium-webdriver\lib\goog\base.js:1094:19), <anonymous>:1857:20)
```

Why is it looking for Safari on my current System? :\

**Comment by verlok** [comment]
The problem happens only if I try to run Safari on SauceLabs.
I tried also to follow the `DesiredCapabilities` values that I found on the [related Selenium wiki page](https://code.google.com/p/selenium/wiki/DesiredCapabilities), as follows:

```json
{
    "seleniumServer": "http://ondemand.saucelabs.com:80/wd/hub",
    "username": "#############",
    "accessKey": "##########################",
    "browserName": "safari",
    "platform": "MAC"
}
```

...but it still doesn't work.

Incredibly, running Firefox on Mac works correctly, with the following browser settings:

```json
{
        "seleniumServer": "http://ondemand.saucelabs.com:80/wd/hub",
        "username": "#############",
        "accessKey": "##########################",
        "browserName": "firefox",
        "platform": "MAC"
    }
```

**Comment by verlok** [comment]
Same problem if I try to run any other browser on SauceLabs.
For example, configuring a browser like the following:

```json
{
    "seleniumServer": "http://ondemand.saucelabs.com:80/wd/hub",
    "username": "#############",
    "accessKey": "##########################",
    "browserName": "internet explorer",
    "platform": "Windows XP",
    "version": "8.0"
}
```

I get the following error:

```console
C:\Code\marvin-demo\node_modules\marvin-js\node_modules\selenium-webdriver\lib\goog\async\nexttick.js:39
  goog.global.setTimeout(function() { throw exception; }, 0);
                                            ^
Error: File does not exist: null
    at Error (<anonymous>)
    at createServiceFromCapabilities (C:\Code\marvin-demo\node_modules\marvin-js\node_modules\selenium-webdriver\ie.
js:386:11)
    at new Driver (C:\Code\marvin-demo\node_modules\marvin-js\node_modules\selenium-webdriver\ie.js:433:17)
    at Builder.build (C:\Code\marvin-demo\node_modules\marvin-js\node_modules\selenium-webdriver\builder.js:466:14)
    at Object.<anonymous> (C:\Code\marvin-demo\node_modules\marvin-js\lib\webdriver\driver-session.js:20:102)
    at promise.ControlFlow.runInFrame_ (eval at <anonymous> (C:\Code\marvin-demo\node_modules\marvin-js\node_modules
\selenium-webdriver\lib\goog\base.js:1094:19), <anonymous>:1857:20)
    at promise.ControlFlow.runEventLoop_ (eval at <anonymous> (C:\Code\marvin-demo\node_modules\marvin-js\node_modul
es\selenium-webdriver\lib\goog\base.js:1094:19), <anonymous>:1729:8)
    at eval (eval at <anonymous> (C:\Code\marvin-demo\node_modules\marvin-js\node_modules\selenium-webdriver\lib\goo
g\base.js:1094:19), <anonymous>:2043:12)
    at goog.async.run.processWorkQueue [as _onTimeout] (C:\Code\marvin-demo\node_modules\marvin-js\node_modules\sele
nium-webdriver\lib\goog\async\run.js:125:21)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
From: Task: <anonymous>
    at Object.module.exports.execute (C:\Code\marvin-demo\node_modules\marvin-js\lib\webdriver\driver-session.js:35:
44)
    at Object.module.exports.create (C:\Code\marvin-demo\node_modules\marvin-js\lib\webdriver\driver-session.js:19:1
7)
    at process.<anonymous> (C:\Code\marvin-demo\node_modules\marvin-js\lib\test-runner\mocha.js:34:13)
    at process.EventEmitter.emit (events.js:98:17)
    at handleMessage (child_process.js:318:10)
    at Pipe.channel.onread (child_process.js:345:11)
```

I tried also to follow the `DesiredCapabilities` values that I found on the [related Selenium wiki page](https://code.google.com/p/selenium/wiki/DesiredCapabilities), as follows:

```json
{
    "seleniumServer": "http://ondemand.saucelabs.com:80/wd/hub",
    "username": "#############",
    "accessKey": "##########################",
    "browserName": "safari",
    "platform": "MAC"
}
```

...but it still doesn't work.

**Comment by verlok** [comment]
I'm looking at SauceLabs test results, and I'm seeing that the last time it worked there was on Wednesday, Sep 2nd. Maybe it depends on SauceLabs subscription, maybe it was our mistake in the code of Marvin... must check

**Comment by verlok** [comment]
I tried with older versions of Marvin, changing the dependency in the marvin-demo repo.
Here's the result of the tests:

0.0.11 OK
0.0.12 OK
0.0.13 OK
0.0.14 ERRORS
0.0.15 ERRORS
0.0.16 ERRORS
0.0.17 ERRORS

So something broke up between 0.0.13 and 0.0.14.

**Comment by verlok** [comment]
I found the commit that's responsible for the tests failure on SauceLabs. It's [this one](https://github.com/brunoscopelliti/marvin/commit/2e0c4f743a3a98719f9a642f6d9c4b85d7c4598f).

The change that breaks the SauceLabs functionality is the following:

```js
(-)    session.browser = msg.browser;
(+)    session.browser = browser;
```

If we revert the line and restore `msg.browser`, it works on SauceLabs, but it doesn't work in local browsers anymore... :-1:

**Comment by brunoscopelliti** [comment]
@verlok thanks for reporting the regression, i will fix as soon as possible...

**Comment by verlok** [comment]
Thank you. It works like a charm now! :+1:
